### ISSUE TITLE
Pip install rtlsdr doesent find a version that satisfie the requirement rtlsdr /No matching distribution found for rtlsdr

### ISSUE THREAD

**Issue by Klammraute** [nootedandrooted/rtl-sdr-close-call-monitor#2]
when i try to install the requirement my system dont find the pip package of rtlsdr

log:
rx@rx:~/rtl-sdr-close-call-monitor$ pip install numpy rtlsdr playsound
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in /home/rx/.local/lib/python3.10/site-packages (1.24.1)
ERROR: Could not find a version that satisfies the requirement rtlsdr (from versions: none)
ERROR: No matching distribution found for rtlsdr

**Comment by nootedandrooted** [comment]
This is not a problem in my script. Like you said: " my system dont find the pip package".
